import fs from 'node:fs';
import react from '@vitejs/plugin-react-swc';
import { componentTagger } from 'lovable-tagger';
import path from 'path';
import { defineConfig, loadEnv, type Plugin } from 'vite';

/**
 * Writes `public/firebase-messaging-sw.js` so deploys and dev never serve
 * `index.html` for that URL (which breaks SW registration with MIME text/html).
 */
function generateFirebaseMessagingSw(): Plugin {
  return {
    name: 'generate-firebase-messaging-sw',
    configResolved(config) {
      const env = loadEnv(config.mode, config.root, 'VITE_');
      const pkg = JSON.parse(
        fs.readFileSync(path.join(config.root, 'package.json'), 'utf-8')
      ) as { dependencies?: { firebase?: string } };
      const raw = pkg.dependencies?.firebase ?? '12.0.0';
      const fbVersion = raw.replace(/^[\^~>=]/, '');

      const firebaseConfig = {
        apiKey: env.VITE_FIREBASE_API_KEY ?? '',
        authDomain: env.VITE_FIREBASE_AUTH_DOMAIN ?? '',
        projectId: env.VITE_FIREBASE_PROJECT_ID ?? '',
        storageBucket: env.VITE_FIREBASE_STORAGE_BUCKET ?? '',
        messagingSenderId: env.VITE_FIREBASE_MESSAGING_SENDER_ID ?? '',
        appId: env.VITE_FIREBASE_APP_ID ?? '',
      };

      const hasAll = Object.values(firebaseConfig).every(
        (v) => typeof v === 'string' && v.length > 0
      );

      const outPath = path.join(config.root, 'public', 'firebase-messaging-sw.js');

      const placeholder = `/* FCM: set VITE_FIREBASE_* in .env (or Vercel env) and restart dev server */
self.addEventListener('install', () => self.skipWaiting());
self.addEventListener('activate', (e) => e.waitUntil(self.clients.claim()));
`;

      const full = `/* Generated by Vite — do not edit by hand */
importScripts('https://www.gstatic.com/firebasejs/${fbVersion}/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/${fbVersion}/firebase-messaging-compat.js');

firebase.initializeApp(${JSON.stringify(firebaseConfig)});

const messaging = firebase.messaging();

messaging.onBackgroundMessage((payload) => {
  const title =
    payload.notification?.title ?? payload.data?.title ?? 'Notification';
  const body = payload.notification?.body ?? payload.data?.body ?? '';
  const icon = payload.notification?.icon ?? payload.data?.icon;
  return self.registration.showNotification(title, {
    body: body || undefined,
    icon: icon || undefined,
  });
});
`;

      fs.mkdirSync(path.dirname(outPath), { recursive: true });
      fs.writeFileSync(outPath, hasAll ? full : placeholder, 'utf-8');
    },
  };
}

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => ({
  server: {
    host: '::',
    port: 8080,
    hmr: {
      overlay: false,
    },
  },
  plugins: [
    generateFirebaseMessagingSw(),
    react(),
    mode === 'development' && componentTagger(),
  ].filter(Boolean),
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
}));
